CREATE LOGIN [FlxAdmin] WITH PASSWORD=N'D1done!', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER LOGIN [FlxAdmin] ENABLE
GO
CREATE LOGIN [FlxReader] WITH PASSWORD=N'D1done!', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER LOGIN [FlxReader] ENABLE
GO
CREATE LOGIN [FlxWriter] WITH PASSWORD=N'D1done!', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER LOGIN [FlxWriter] ENABLE
GO

USE [MASTER];
GRANT VIEW SERVER STATE TO [FlxAdmin];
GRANT ALTER ON LOGIN::FlxReader TO FlxAdmin;
GRANT ALTER ON LOGIN::FlxWriter TO FlxAdmin;
GO

USE [Apriso]
GO
ALTER USER [FlxAdmin] With LOGIN=FlxAdmin
GO
ALTER USER [FlxReader] With LOGIN=FlxReader
GO
ALTER USER [FlxWriter] With LOGIN=FlxWriter
GO